version: '3.9'

services:
  db:
    image: mariadb:10.5
    hostname: mariadb
    container_name: hibernate_test_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hibernateTest
      MARIADB_USER: user
      MARIADB_PASSWORD: userpass
    ports:
      - "3307:3306"